services:
  database:
    container_name: solpayg-postgres
    image: postgres:18
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: solpay
    ports:
      - "5432:5432"
    volumes:
      - ./databasepg:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d solpay"]
      interval: 10s
      timeout: 5s
      retries: 5
