services:
  database:
    container_name: solpayg-postgres
    image: postgres:18
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: solpay
    ports:
      - "5432:5432"
    volumes:
      - ./databasepg:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d solpay"]
      interval: 10s
      timeout: 5s
      retries: 5

  solpay-core-service:
    container_name: solpay-core-service
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: solpay
